name: js
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout
        run: |
          pwd

      - name: Update
        run: python sc/UpdateJS.py

      - name: Commit
        run: |
          git pull origin main
          git config --local user.email "123@gmail.com"
          git config --local user.name "Gene"
          git add ./*
          git commit -m "UpdateJS" -a
      - name: Push file
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
