name: js
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout
        run: |
          pwd

      - name: 更新
        run: python Scripts/UpdateJS.py

      - name: Commit and push changes
        run: |
         if [[ -n $(git status -s) ]]; then
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add ./*
           git commit -m "UpdateJS" -a
           git pull origin main
         else
          echo "No changes to commit."
         fi

      - name: "推送文件"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
