name: fork 

on:
  workflow_dispatch:

  
jobs:
  fork:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: SouthAlley/t
        path: t-repo

   
    - name: Download file to Surge
      run: |
        mkdir -p t-repo/rule/

        # 广告规则 
        curl -L -o t-repo/rule/Adblock4limbo.user.js "https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adguard/Adblock4limbo.user.js"


    - name: Edit rule/ad
      run: |
        cd t-repo/rule
        for file in Adblock4limbo.user.js; do
          if [ -f "$file" ]; then
            # DOMAIN, 移除
            sed -i '/daohang_build();/i \\//' "$file"
          else
            echo "$file not found."
          fi
        done


    - name: Add and Commits
      run: |
        cd t-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add rule/* 
          git commit -m "Update"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi
