name: fork 

on:
  workflow_dispatch:
  schedule:
    - cron: "15 20 * * *"

  
jobs:
  fork:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: SouthAlley/t
        path: t-repo

   
    - name: Download file to Surge
      run: |
        mkdir -p t-repo/rule/

        # 广告规则 
        curl -L -o t-repo/rule/cnip.txt "https://raw.githubusercontent.com/SouthAlley/q/main/rule/chinaip/fin.txt"


    - name: Edit rule/ad
      run: |
        cd t-repo/rule
        for file in cnip.txt; do
          if [ -f "$file" ]; then
            # DOMAIN, 移除
            sed -i 's/IP-CIDR,//g' "$file"
            # 删除不必要的部分
            sed -i 's/,no-resolve//g' "$file"
            # 删除注释
            sed -i 's/#.*//' "$file"
            # 删除空行
            sed -i '/^[[:space:]]*$/d' "$file"
          else
            echo "$file not found."
          fi
        done


    - name: Add and Commits
      run: |
        cd t-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add rule/* 
          git commit -m "Update"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi
