name: Update Rules

on:
  workflow_dispatch:

jobs:
  update_rules:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "启动任务"
      run: |
          pwd

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install gitpython requests

    - name: Run Python script
      run: |
        cd Scripts  # 进入脚本目录
        python rule.py
    - name: "提交文件"
      run: |
       git checkout main  # 切换到主分支
       git pull origin main
       git config --local user.email "123@gmail.com"
       git config --local user.name "Gene"
       git add ./*
       git commit -m "Update Rules" -a
    - name: "推送文件"
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

